apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: ${KUBERNETES_NAMESPACE}
spec:
  clusterIP: None
  ports:
  - name: default
    port: ${APP_DB_PORTA}
    protocol: TCP
    targetPort: ${APP_DB_PORTA}
  selector:
    servico: db
  sessionAffinity: None
  type: ClusterIP

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: ${KUBERNETES_NAMESPACE}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      servico: db
  serviceName: db
  template:
    metadata:
      annotations:
      labels:
        servico: db
    spec:
      affinity: {}
      containers:
        - env:
            - name: ${APP_DB_PASSWORD}
              valueFrom:
                secretKeyRef:
                  key: APP_DB_ROOT_PASSWORD
                  name: sei-secret1
                  optional: false
          image: ${REGISTRY}/${REGISTRY_PROJECT}/${IMAGE_DB}
          imagePullPolicy: Always
          name: db
          resources:
            limits:
              cpu: ${KUBERNETES_LIMITS_CPU_DB}
              memory: ${KUBERNETES_LIMITS_MEMORY_DB}
            requests:
              cpu: ${KUBERNETES_REQUEST_CPU_DB}
              memory: ${KUBERNETES_REQUEST_MEMORY_DB}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: ${APP_DB_MOUNT_PATH}
              name: vol1
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ${REGISTRY_NAME}
      initContainers:
      - command:
        - bash
        - -c
        - echo "Vamos verificar se existe uma pasta com os dados do mysql."; echo
          "Caso nao exista vamos criar..."; i=$(ls -A --ignore='lost+found' /t);  if [[ "$(ls -A --ignore='lost+found' /t)" = "" ]]; then     echo
          "Diretorio vazio, vamos copiar os dados do banco...";     cp -a ${APP_DB_MOUNT_PATH}/*
          /t/ &&     echo "Dados copiados!"; else   echo "Diretorio nao esta vazio.
          " ;   echo "Arquivos encontrados";    i=$(ls -lha --ignore='lost+found' /t);   echo $(ls -A --ignore='lost+found' /t);   echo
          "Nao vamos alterar nada. " ;   echo "Caso o banco nao suba, verifique se
          nesse dir existe um banco e que as permissoes do arquivo estejam com o mysql
          (id 999)" ; fi;  exit 0
        image: ${REGISTRY}/${REGISTRY_PROJECT}/${IMAGE_DB}
        imagePullPolicy: Always
        name: db-init
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /t
          name: vol1
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: vol-sei-db
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate


---

apiVersion: v1
kind: Service
metadata:
  name: solr
  namespace: ${KUBERNETES_NAMESPACE}
spec:
  clusterIP: None
  ports:
  - name: default
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    servico: solr
  sessionAffinity: None
  type: ClusterIP


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
  namespace: ${KUBERNETES_NAMESPACE}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      servico: solr
  serviceName: solr
  template:
    metadata:
      labels:
        servico: solr
    spec:
      containers:
      - image: ${REGISTRY}/${REGISTRY_PROJECT}/${IMAGE_SOLR}
        imagePullPolicy: Always
        name: solr
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /solr/admin/info/system
            port: 8983
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /solr/admin/info/system
            port: 8983
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: ${KUBERNETES_LIMITS_CPU_SOLR}
            memory: ${KUBERNETES_LIMITS_MEMORY_SOLR}
          requests:
            cpu: ${KUBERNETES_REQUEST_CPU_SOLR}
            memory: ${KUBERNETES_REQUEST_MEMORY_SOLR}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /dados
          name: vol1
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ${REGISTRY_NAME}
      initContainers:
        - command:
          - bash
          - -c
          - echo "Vamos verificar se existe uma pasta com os dados do solr."; echo
            "Caso nao exista vamos criar..."; if [[ "$(ls -A --ignore='lost+found' /t)" = "" ]]; then
            echo "Diretorio vazio, vamos copiar os dados do solr..."; cp -a /dados/*
            /t/ && echo "Dados copiados!"; else echo "Diretorio nao esta vazio. " ;
            echo "Arquivos encontrados"; echo $(ls -lha --ignore='lost+found' /t); echo "Nao vamos alterar
            nada. " ; echo "Caso o solr nao suba, verifique se nesse dir existe um
            solr e que as permissoes do arquivo estejam com o Solr (id 1000)" ; fi;  exit
            0
          image: ${REGISTRY}/${REGISTRY_PROJECT}/${IMAGE_SOLR}
          imagePullPolicy: Always
          name: solr-init
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /t
            name: vol1
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: vol-sei-solr
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate